POST http://localhost:3000/api/complaints
Content-Type: application/json

{
  "name": "Rohit",
  "description": "lights not working properly near the entrance of the building",
  "files": null
}

###
http://localhost:3000/admin